linux 6.7.8
commit d6d6c49dbf4512f1421f5e42896e2d70dc121f9a
Author: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Date:   Sat Mar 2 18:23:50 2024 +0100

    Linux 6.7.8

    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit 1752a632a68268573a92a18d9d656cf0c8fccfc2
Author: Mark O'Donovan <shiftee@posteo.net>
Date:   Wed Feb 21 10:43:58 2024 +0000

    fs/ntfs3: fix build without CONFIG_NTFS3_LZX_XPRESS

    commit c8e314624a1666ed2eec28549713021a8ec801e9 upstream.

    When CONFIG_NTFS3_LZX_XPRESS is not set then we get the following build
    error:

      fs/ntfs3/frecord.c:2460:16: error: unused variable ‘i_size’

    Signed-off-by: Mark O'Donovan <shiftee@posteo.net>
    Fixes: 4fd6c08a16d7 ("fs/ntfs3: Use i_size_read and i_size_write")
    Tested-by: Chris Clayton <chris2553@googlemail.com>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
    Reported-by: Rainer Fiebig <jrf@mailbox.org>
    Cc: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>